# .github/workflows/generate-code.yml

name: Generate gRPC Go Code

on:
  push:
    paths:
      - 'protos/**'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install protoc and Go plugins
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Generate Go gRPC code for all .proto files
        run: |
          OUT_DIR=internal/gen
          rm -rf $OUT_DIR
          mkdir -p $OUT_DIR

          for file in $(find protos -name "*.proto"); do
            protoc -Iprotos \
              --go_out=$OUT_DIR --go_opt=paths=source_relative \
              --go-grpc_out=$OUT_DIR --go-grpc_opt=paths=source_relative \
              "$file"
          done

      - name: Format generated Go code
        run: |
          go fmt ./internal/gen/...

      - name: Commit and push generated code
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add internal/gen/
          git diff --cached --quiet || (git commit -m "Auto-generate Go gRPC code from proto update" && git push)
 